<?php
return [
    [
        'name' => 'addondev',
        'title' => '插件开发代码生成器',
        'icon' => 'fa fa-magic',
        'ismenu' => 1,
        'py' => 'cjkfdmscq',
        'pinyin' => 'chajiankaifadaimashengchengqi',
        'sublist' =>
        [
            [
                'name' => 'addondev/addon',
                'title' => '插件项目',
                'icon' => 'fa fa-cubes',
                'ismenu' => 1,
                'py' => 'cjxm',
                'pinyin' => 'chajianxiangmu',
                'remark' => '提示生产环境务必禁用此插件并关闭调试模式',
                'weigh' => 10,
                'sublist' =>
                [
                    [
                        'name' => 'addondev/addon/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'zk',
                        'pinyin' => 'zhakan',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/addon/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'tj',
                        'pinyin' => 'tianjia',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/addon/edit',
                        'title' => '编辑生成代码',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'bjscdm',
                        'pinyin' => 'bianjishengchengdaima',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/addon/exportmenu',
                        'title' => '导出菜单',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'dccd',
                        'pinyin' => 'daochucaidan',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/addon/backup',
                        'title' => '备份代码模版',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'bfdmmb',
                        'pinyin' => 'beifengdaimamoban',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/addon/restore',
                        'title' => '回复代码模版',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'hfdmmb',
                        'pinyin' => 'huifudaimamoban',
                        'weigh' => 0,
                    ],
                ],
            ],
            [
                'name' => 'addondev/gen',
                'title' => '代码管理',
                'icon' => 'fa fa-code',
                'ismenu' => 1,
                'py' => 'dmgl',
                'pinyin' => 'daimaguanli',
                'remark' => '提示生产环境务必禁用此插件并关闭调试模式',
                'weigh' => 2,
                'sublist' =>
                [
                    [
                        'name' => 'addondev/gen/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'zk',
                        'pinyin' => 'zhakan',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/gen/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'tj',
                        'pinyin' => 'tianjia',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/gen/edit',
                        'title' => '编辑生成代码',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'bjscdm',
                        'pinyin' => 'bianjishengchengdaima',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/gen/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'sc',
                        'pinyin' => 'shanchu',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/gen/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'plgx',
                        'pinyin' => 'pilianggengxin',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/gen/code',
                        'title' => '预览代码',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'yldm',
                        'pinyin' => 'yulandaima',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/gen/diff',
                        'title' => '对比代码',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'dbdm',
                        'pinyin' => 'duibidaima',
                        'weigh' => 0,
                    ],
                ],
            ],
            [
                'name' => 'addondev/log',
                'title' => '代码文件日志',
                'icon' => 'fa fa-history',
                'ismenu' => 1,
                'py' => 'dmwjrz',
                'pinyin' => 'daimawenjianrizhi',
                'remark' => '记录被代码生成器覆盖前的文件，可以预览，对比本地代码，恢复代码;提示生产环境务必禁用此插件并关闭调试模式',
                'weigh' => 1,
                'sublist' =>
                [
                    [
                        'name' => 'addondev/log/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'zk',
                        'pinyin' => 'zhakan',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/log/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'sc',
                        'pinyin' => 'shanchu',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/log/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'plgx',
                        'pinyin' => 'pilianggengxin',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/log/diff',
                        'title' => '对比本地代码',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'dbbddm',
                        'pinyin' => 'duibibendidaima',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/log/code',
                        'title' => '预览代码',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'yldm',
                        'pinyin' => 'yulandaima',
                        'weigh' => 0,
                    ],
                    [
                        'name' => 'addondev/log/recover',
                        'title' => '回复文件',
                        'icon' => 'fa fa-circle-o',
                        'ismenu' => 0,
                        'py' => 'hfwj',
                        'pinyin' => 'huifuwenjian',
                        'weigh' => 0,
                    ],
                ],
            ],
        ],
    ],
];
